name: Trigger Semgrep Static Code Analysis

on:
  pull_request:
  
permissions:
    actions: write
    contents: write
    pull-requests: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use composite action from another repo
        uses: Sinnay-p/sempgrep/.github/actions/semgrep-scan@main

