name: Trigger Semgrep Static Code Analysis

on:
  pull_request:
  
permissions:
    contents: write
    pull-requests: write
    
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Dispatch an action and get the run ID
        uses: anecdotes-ai/remote-workflow-control@latest
        id: return_dispatch
        with:
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}
          workflow-org: 'Sinnay-p'
          workflow-repo: 'sempgrep'
          workflow-yaml: 'semgrep-scan.yaml'
          workflow-branch: 'main'
          wait-timeout-in-minutes: '10'
