name: Trigger Semgrep Static Code Analysis

on:
  pull_request:
  
permissions:
    actions: write
    contents: write
    pull-requests: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Sinnay-p/sempgrep/dispatches \
            -d "{\"event_type\": \"trigger-workflow\"}"
